In [1]:
%pip install pandas
%pip install numpy
%pip install matplotib
%pip install nltk
%pip install wordcloud
%pip install langdetect

Requirement already satisfied: pandas in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (2.3.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement matplotib (from versions: none)
ERROR: No matching distribution found for matplotib

Requirement already satisfied: nltk in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2025.7.34)
Requirement already satisfied: tqdm in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: wordcloud in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (1.9.4)
Requirement already satisfied: numpy>=1.6.1 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from wordcloud) (2.3.1)
Requirement already satisfied: pillow in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from wordcloud) (11.3.0)
Requirement already satisfied: matplotlib in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from wordcloud) (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->wordcloud) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->wordcloud) (4.58.5)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->wordcloud) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->wordcloud) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->wordcloud) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: langdetect in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (1.0.9)
Requirement already satisfied: six in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (from langdetect) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('books.csv', encoding="utf-8-sig")


df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   titre          1000 non-null   object
 1   description    998 non-null    object
 2   prix           1000 non-null   object
 3   disponibilité  1000 non-null   object
 4   image          1000 non-null   object
 5   note           1000 non-null   object
dtypes: object(6)
memory usage: 47.0+ KB

In [4]:
df

,titre,description,prix,disponibilité,image,note
0,A Light in the Attic,It's hard to imagine a world without A Light i...,£51.77,In stock,https://books.toscrape.com/media/cache/2c/da/2...,Three
1,Tipping the Velvet,"""Erotic and absorbing...Written with starling ...",£53.74,In stock,https://books.toscrape.com/media/cache/26/0c/2...,One
2,Soumission,"Dans une France assez proche de la nôtre, un h...",£50.10,In stock,https://books.toscrape.com/media/cache/3e/ef/3...,One
3,Sharp Objects,"WICKED above her hipbone, GIRL across her hear...",£47.82,In stock,https://books.toscrape.com/media/cache/32/51/3...,Four
4,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,£54.23,In stock,https://books.toscrape.com/media/cache/be/a5/b...,Five
...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,NaN,£55.53,In stock,https://books.toscrape.com/media/cache/96/ee/9...,One
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",High school student Kei Nagai is struck dead i...,£57.06,In stock,https://books.toscrape.com/media/cache/09/7c/0...,Four
997,A Spy's Devotion (The Regency Spies of London #1),"In England’s Regency era, manners and elegance...",£16.97,In stock,https://books.toscrape.com/media/cache/1b/5f/1...,Five
998,1st to Die (Women's Murder Club #1),"James Patterson, bestselling author of the Ale...",£53.98,In stock,https://books.toscrape.com/media/cache/2b/41/2...,One
999,"1,000 Places to See Before You Die","Around the World, continent by continent, here...",£26.08,In stock,https://books.toscrape.com/media/cache/d7/0f/d...,Five

In [5]:
import pandas as pd
import re
import numpy as np


df = pd.read_csv('books.csv', encoding="utf-8-sig")


df.columns = df.columns.str.strip().str.lower()


df.rename(columns={'disponibilité': 'disponibilite'}, inplace=True)


def nettoyer_description(desc):
    if pd.isna(desc):
        return ""
    desc = re.sub(r'\s+', ' ', desc)
    desc = re.sub(r'[^A-Za-z0-9À-ÖØ-öø-ÿ\s]', '', desc)  
    return desc.strip()

df['description'] = df['description'].apply(nettoyer_description)


df['prix'] = df['prix'].replace('[\£,]', '', regex=True).astype(float)

df['disponibilite'] = df['disponibilite'].str.extract(r'(\d+)').astype(float).fillna(0).astype(int)

note_mapping = {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
df['note'] = df['note'].map(note_mapping)


df['description'] = df['description'].replace('', np.nan)
df['description'] = df['description'].fillna(df['titre'])

df.to_csv('livres_bruts.csv', index=False)

data = pd.read_csv('livres_bruts.csv')

data
print(df["note"].dtype)

int64

In [6]:
%pip install stop_words

Requirement already satisfied: stop_words in c:\users\a\appdata\local\programs\python\python313\lib\site-packages (2018.7.23)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
from langdetect import detect
from stop_words import get_stop_words



data["lang"] = data["description"].apply(lambda x: detect(str(x)) if pd.notnull(x) else "unknown")


stop_fr = set(get_stop_words("french"))
stop_en = set(get_stop_words("english"))

stop_all = list(set(stop_en).union(set(stop_fr)))


print(data["lang"].value_counts())

lang
en    999
fr      1
Name: count, dtype: int64

In [8]:
data

,titre,description,prix,disponibilite,image,note,lang
0,A Light in the Attic,Its hard to imagine a world without A Light in...,51.77,0,https://books.toscrape.com/media/cache/2c/da/2...,3,en
1,Tipping the Velvet,Erotic and absorbingWritten with starling powe...,53.74,0,https://books.toscrape.com/media/cache/26/0c/2...,1,en
2,Soumission,Dans une France assez proche de la nôtre un ho...,50.10,0,https://books.toscrape.com/media/cache/3e/ef/3...,1,fr
3,Sharp Objects,WICKED above her hipbone GIRL across her heart...,47.82,0,https://books.toscrape.com/media/cache/32/51/3...,4,en
4,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,54.23,0,https://books.toscrape.com/media/cache/be/a5/b...,5,en
...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Alice in Wonderland (Alice's Adventures in Won...,55.53,0,https://books.toscrape.com/media/cache/96/ee/9...,1,en
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",High school student Kei Nagai is struck dead i...,57.06,0,https://books.toscrape.com/media/cache/09/7c/0...,4,en
997,A Spy's Devotion (The Regency Spies of London #1),In Englands Regency era manners and elegance r...,16.97,0,https://books.toscrape.com/media/cache/1b/5f/1...,5,en
998,1st to Die (Women's Murder Club #1),James Patterson bestselling author of the Alex...,53.98,0,https://books.toscrape.com/media/cache/2b/41/2...,1,en
999,"1,000 Places to See Before You Die",Around the World continent by continent here i...,26.08,0,https://books.toscrape.com/media/cache/d7/0f/d...,5,en

In [9]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity
import joblib


vectorizer = TfidfVectorizer(stop_words=stop_all)

matrix = vectorizer.fit_transform(data['description'])

similarity = cosine_similarity(matrix, matrix)


joblib.dump(similarity, "similarite_livres.pkl")
joblib.dump(vectorizer, "vectoriseur.pkl")
joblib.dump(data, "data_livres.pkl")


def recommander_multilingue(titre, top_n=5):
    if titre not in data['titre'].values:
        return []
    
    idx = data.index[data['titre'] == titre][0]
    scores = list(enumerate(similarity[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    scores = [s for s in scores if s[0] != idx][:top_n]
    
    livres_suggest = data.iloc[[s[0] for s in scores]]
    return livres_suggest[['titre', 'prix', 'note', 'disponibilite']].to_dict(orient='records')

exemple = recommander_multilingue("Titre d'exemple", 3)
print(exemple)

c:\Users\a\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['aren', 'can', 'couldn', 'didn', 'doesn', 'don', 'hadn', 'hasn', 'haven', 'isn', 'let', 'll', 'mustn', 're', 'shan', 'shouldn', 've', 'wasn', 'weren', 'won', 'wouldn'] not in stop_words.
  warnings.warn(

[]